trigger:
- main

pool:
  name: Default

variables:
- group: 'First AWS-Deployment'

steps:

- checkout: self

- script: |
    echo "Repository Files"
    dir
  displayName: "Verify Repository"

- script: |
    echo "Testing SSH Connection..."
    ssh -o StrictHostKeyChecking=no -i "C:\Sravani\CICD-AWS\AWS-CICD.pem" $(EC2_USER)@$(EC2_IP) "echo SSH Connection Successful"
  displayName: "Test SSH"

- script: |
    echo "Copying Website..."
    scp -o StrictHostKeyChecking=no -i "C:\Sravani\CICD-AWS\AWS-CICD.pem" index.html $(EC2_USER)@$(EC2_IP):/home/ec2-user/
  displayName: "Copy Website"

- script: |
    echo "Deploying Website..."
    ssh -o StrictHostKeyChecking=no -i "C:\Sravani\CICD-AWS\AWS-CICD.pem" $(EC2_USER)@$(EC2_IP) "sudo cp /home/ec2-user/index.html $(WEB_PATH)/index.html"
  displayName: "Deploy Website"

- script: |
    echo "Deployment Completed Successfully"
  displayName: "Deployment Status"